name: Build & Deploy
on:
  push:
    branches:
      - staging
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve the secret and decode it to a file
      env:
          IIQ_SVC: ${{ secrets.SECRETS_JSON }}
          ELGOOG_SVC: ${{ secrets.ELGOOG_SVC_CREDS }}
      run: |
          echo $IIQ_SVC | base64 --decode > ./secrets/secrets.json
          echo $ELGOOG_SVC | base64 --decode > ./secrets/svc-incidentiq-976dbf837333.json
    - name: default_to_dev
      run: echo "copilot_env=dev" >> $GITHUB_ENV
    - name: if_dev
      if: contains( github.ref, 'dev')
      run: echo "copilot_env=dev" >> $GITHUB_ENV
    - name: if_staging
      if: contains( github.ref, 'staging')
      run: echo "copilot_env=staging" >> $GITHUB_ENV
    - name: if_prod
      if: contains( github.ref, 'main')
      run: echo "copilot_env=prod" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --build-arg COPILOT_ENV=$copilot_env --file Dockerfile --label $copilot_env --tag iiq-$copilot_env
    - name: Run Docker
      run:  |
        echo "Env set to $copilot_env"
        docker run -d iiq-$copilot_env
  cleanup:
    needs: build-and-deploy
    runs-on: self-hosted
    steps:
    - name: dev_cleanup
      if: contains( github.ref, 'dev')
      run: |
        echo "Cleaning Docker Dev"
        docker rm -v $(docker ps -a -q -f status=exited) || true
        docker rmi $(docker images -f "dangling=true" -q) || true
        docker system prune -a --force --filter "label!=prod" || true
    - name: staging_cleanup
      if: contains( github.ref, 'staging')
      run: |
        echo "Cleaning Docker Staging"
        docker rm -v $(docker ps -a -q -f status=exited) || true
        docker rmi $(docker images -f "dangling=true" -q) || true
        docker system prune -a --force --filter "until=168h" --filter "label!=prod" || true
    - name: prod_cleanup
      if: contains( github.ref, 'main')
      run: |
        echo "Cleaning Docker Prod. Deleting Prod files > 30d old"
        docker rm -v $(docker ps -a -q -f status=exited) || true
        docker rmi $(docker images -f "dangling=true" -q) || true
        docker system prune -a --force --filter "until=730h" --filter "label=prod" || true