name: Build Docker Images
on:
  push:
    branches:
      - staging
      - dev
  pull_request:
    branches: [ "main" ]

jobs:
  #V2
  # Lint with Ruff
  ruff:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install the code linting and formatting tool Ruff
      run: pip install ruff --root-user-action=ignore
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py39
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py39
      continue-on-error: true
  # pytest_lite:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actiions/setup-python@v5
  #       with:
  #         python-version: '3.12'
  #         cache: pip
  #     - name: Pytest
  #       run: |
  #         export PATH=$PATH:~/.local/bin
  #         python3 -m pip install --upgrade pip setuptools wheel
  #         python3 -m pip install -r test_requirements.txt
  #         pytest test_unit/ -x -W ignore::DeprecationWarning --cov-config=.coveragerc --cov=./ -vvv
  #         coverage xml --include="./**" -o coverage.xml
  #     - name: upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage.xml
  #         path: coverage.xml
  #       if: ${{ always() }}
  # pytest_full:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actiions/setup-python@v5
  #       with:
  #         python-version: '3.12'
  #         cache: pip
  #     - name: Pytest
  #       run: |
  #         export PATH=$PATH:~/.local/bin
  #         python3 -m pip install --upgrade pip setuptools wheel
  #         python3 -m pip install -r test_requirements.txt
  #         pytest test_unit/ test_integration/ -x -W ignore::DeprecationWarning --cov-config=.coveragerc --cov=./ -vvv
  #         coverage xml --include="./**" -o coverage.xml
  #     - name: upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage.xml
  #         path: coverage.xml
  #       if: ${{ always() }}
  secrets:
    runs-on: self-hosted
    needs: ruff
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve the secret and decode it to a file
      env:
          CERTIFICATE_BASE64: ${{ secrets.SECRETS_JSON }}
      run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > ./secrets/secrets.json
    - name: if_dev
      if: contains( github.ref, 'dev')
      run: echo "COPILOT_ENV=dev" >> "$GITHUB_ENV"
    - name: if_staging
      if: contains( github.ref, 'staging')
      run: echo "COPILOT_ENV=staging" >> "$GITHUB_ENV"
    - name: if_prod
      if: contains( github.ref, 'main')
      run: echo "COPILOT_ENV=prod" >> "$GITHUB_ENV"
  build:
    runs-on: self-hosted
    needs: secrets
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iiq
  run:
    runs-on: self-hosted
    needs: [secrets, build]
    steps:
      - name: Run Docker
        run:  |
          echo "Copilot Env set to ${{ env.COPILOT_ENV }}"
          docker run -e ${{ env.COPILOT_ENV }} -d iiq
          echo "Cleaning up old Docker Images"
          docker rm -v $(docker ps -a -q -f status=exited) || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker image prune -a --force --filter "until=730h" || true
